# Simulation settings for using moveit_sim_controllers
moveit_sim_hw_interface:
  joint_model_group: hong_arm
  joint_model_group_pose: todo_no_pose_selected
# Settings for ros_control_boilerplate control loop
generic_hw_control_loop:
  loop_hz: 300
  cycle_time_error_threshold: 0.01
# Settings for ros_control hardware interface
hardware_interface:
  joints:
    - hong_shoulder_pan_joint
    - hong_shoulder_lift_joint
    - hong_elbow_joint
    - hong_wrist_1_joint
    - hong_wrist_2_joint
    - hong_wrist_3_joint
    - kong_shoulder_pan_joint
    - kong_shoulder_lift_joint
    - kong_elbow_joint
    - kong_wrist_1_joint
    - kong_wrist_2_joint
    - kong_wrist_3_joint
    - rigid_joint
  sim_control_mode: 1  # 0: position, 1: velocity
# Publish all joint states
# Creates the /joint_states topic necessary in ROS
joint_state_controller:
  type: joint_state_controller/JointStateController
  publish_rate: 50
controller_list:
  []
arm_position_controller:
  type: position_controllers/JointPositionController
  joints:
    - hong_shoulder_pan_joint
    - hong_shoulder_lift_joint
    - hong_elbow_joint
    - hong_wrist_1_joint
    - hong_wrist_2_joint
    - hong_wrist_3_joint
    - kong_shoulder_pan_joint
    - kong_shoulder_lift_joint
    - kong_elbow_joint
    - kong_wrist_1_joint
    - kong_wrist_2_joint
    - kong_wrist_3_joint
    - rigid_joint
  gains:
    hong_shoulder_pan_joint:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    hong_shoulder_lift_joint:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    hong_elbow_joint:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    hong_wrist_1_joint:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    hong_wrist_2_joint:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    hong_wrist_3_joint:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    kong_shoulder_pan_joint:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    kong_shoulder_lift_joint:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    kong_elbow_joint:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    kong_wrist_1_joint:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    kong_wrist_2_joint:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    kong_wrist_3_joint:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    rigid_joint:
      p: 100
      d: 1
      i: 1
      i_clamp: 1